name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set UUID
      id: generate-uuid
      uses: filipstefansson/uuid-action@v1
      with:
       name: ${{ github.sha }}
      # use the output from the `generate-uuid` step
    - name: Get the UUID
      run: echo "UUID is ${{ steps.generate-uuid.outputs.uuid }}"
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore   
    - name: Test AbstractionCode
      run: dotnet test test\BarbellTracker.AbstractionCodeTests\BarbellTracker.AbstractionCodeTests.csproj
    - name: Test DomainCode
      run: dotnet test test\BarbellTracker.DomainCodeTests\BarbellTracker.DomainCodeTests.csproj
    - name: Test ApplicationCode
      run: dotnet test test\BarbellTracker.ApplicationCode_Tester\BarbellTracker.ApplicationCodeTestes.csproj
    - name: Test Adapter
      run: dotnet test test\BarbellTracker.AdapterTests\BarbellTracker.AdapterTests.csproj
    - name: Test Services
      run: dotnet test test\BarbellTracker.ServicesTests\BarbellTracker.ServicesTests.csproj
    - name: publish
      run: dotnet publish src\BarbellTracker.WPF_DesktopClient\BarbellTracker.WPF_DesktopClient.csproj -c Release --self-contained -r win-x64 -p:PublishSingleFile=true -p:IncludeNativeLibrariesForSelfExtract=true
    - name: name Realse
      uses: actions/create-release@v1
      id: create_release
      env:
       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
       tag_name: ${{ steps.generate-uuid.outputs.uuid }}
       release_name: ${{ github.event.head_commit.message }}
    - name: upload
      uses: csexton/release-asset-action@v2
      with:
       github-token: ${{ secrets.GITHUB_TOKEN }}
       pattern: src\BarbellTracker.WPF_DesktopClient\bin\Release\net6.0-windows\win-x64\publish\*.exe
       release-url: ${{ steps.create_release.outputs.upload_url }}
